import { StyleSheet } from 'react-native';
import { ms } from "react-native-size-matters";


const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: 'column',
    width: "100%",
    padding: ms(10),
    height: "auto",
    zIndex: 1,
    overflow: 'hidden',
  },
  scrollContent: {
    paddingBottom: ms(50),
  },
  section: {
    width: "97%",
    height: 'auto',
    marginBottom: ms(14),
  },
  sectionTitle: {
    textAlign: "center",
    fontSize: ms(18),
    fontWeight: "bold",
    marginBottom: ms(8),
    color: "000000",
  },
  description: {
    fontSize: ms(13),
    marginBottom: ms(8),
    letterSpacing: ms(0.5),
    color: "#244057B5",
  },
  imageContainer: {
    width: "95%",
    height: ms(437),
    borderRadius: ms(12),
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  searchBarContainer: {
    width: "100%",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  overlayImage: {
    position: 'absolute',
    bottom: ms(-100),
    width: "100%",
    height: "100%",
    borderRadius: ms(12),
  },
  horizontalLine: {
    width: "100%",
    height: 1,
    backgroundColor: "#CFCFCF",
    marginBottom: ms(10),
  },
  headingText: {
    position: "absolute",
    top: ms(20),
    left: ms(15),
    fontSize: ms(20),
    fontWeight: "bold",
    fontFamily: "Lato",
    lineHeight: 24 * 1.4,
    letterSpacing: 0,
    textAlign: "center",
    color: "#FFFFFF",
  },
  subHeadingText: {
    position: "absolute",
    top: ms(55),
    left: ms(15),
    width: "90%",
    fontSize: ms(14),
    fontFamily: "Lato",
    lineHeight: ms(20),
    textAlign: "left",
    color: "#FFFFFF",
  },
  buttonContainer: {
    position: "absolute",
    top: ms(120),
    left: ms(8),
    right: ms(8),
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    width: "99%",
    zIndex: 2,
  },
  customButton: {
    margin: ms(5),
    backgroundColor: "rgba(255, 255, 255, 0.42)",
    paddingVertical: ms(5),
    paddingHorizontal: ms(20),
    borderRadius: ms(35),
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: ms(14),
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  newButton: {
    position: 'absolute',
    top: ms(340),
    alignSelf: 'center',
    width: ms(125),
    height: ms(38),
    backgroundColor: "#DE3F35",
    justifyContent: "center",
    alignItems: "center",
    // padding: ms(10),
    borderRadius: ms(6),
    zIndex: 2,
  },
  newButtonText: {
    color: "#FFFFFF",
    fontSize: ms(14),
    fontWeight: "bold",
    fontFamily: "Lato",
  },
  boxcontainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    alignItems: 'center',
    paddingHorizontal: ms(10),
    marginTop: ms(-58),
    marginBottom: ms(10),
    width: "100%",
  },
  box: {
    width: "30%",
    height: ms(90),
    justifyContent: 'center',
    alignItems: 'center',
    padding: ms(5),
    marginVertical: ms(10),
    borderRadius: ms(6),
    borderWidth: 2,
    backgroundColor: 'white',
    borderColor: 'rgba(128, 128, 128, 0.5)',
    position: 'relative',
  },
  boxImage: {
    width: ms(24),
    height: ms(24),
    position: 'absolute',
    top: ms(5),
    alignSelf: 'center',
  },
  boxText: {
    marginTop: ms(30),
    fontSize: ms(12),
    fontFamily: "Lato-Semibold",
    lineHeight: ms(16),
    color: "#09346C",
    textAlign: 'center',
  },

  // Browse Categories styles section
  BowserCategorycontainer: {
    width: ms(100),
    height: ms(100),
    borderRadius: ms(10),
    overflow: "hidden",
    position: 'relative',
    marginBottom: ms(10),
    margin: ms(5),
    borderWidth: 1,
    borderColor: "#cfcfcf",

  },
  BowserCategorybg: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: ms(10),
    borderRadius: ms(10),
  },
  BowserCategoryText: {
    width: "80%",
    position: 'absolute',
    fontSize: ms(14),
    fontFamily: "Lato-Semibold",
    fontWeight: ms(700),
    lineHeight: ms(20),
    color: "#140B41",
    marginLeft: ms(10),
    marginTop: ms(5),
    textAlign: 'left',
    height: 'auto',
  },
  RecommendedCheckupContainer: {
    position: 'relative',
    width: ms(154),
    height: ms(165),
    borderRadius: ms(10),
    // marginBottom: ms(20),
    margin: ms(5),
    backgroundColor: 'rgba(200, 175, 213, 0.6)',
  },
  RecommendedCheckupContainer1: {

    width: ms(130),
    height: ms(93),
    backgroundColor: '#C8AFD5',
    alignSelf: 'center',
    borderRadius: ms(10),
    marginTop: ms(15),
    position: 'relative',
  },
  RecommendedCheckupButton: {
    width: '80%',
    alignItems: 'center',
    paddingVertical: ms(5),
    borderRadius: ms(29),
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    alignSelf: 'center',
    marginTop: ms(10),

  },
  RecommendedCheckupContainerImage: {
    height: ms(93),
    width: ms(98),
    position: 'absolute',
    left: ms(10)
  },
  RecommendedCheckupText: {
    color: 'black',
    textAlign: 'center',
    width: '100%',
    fontSize: ms(13),
    padding: ms(2)
  },
  RecomChkupContainerImageMen: {
    height: ms(93),
    width: ms(125),
    position: 'absolute',
    // top: ms(-10),
    alignSelf: 'center',
    // left: ms(10)
  },
  toppackages: {
    height: ms(100),
    width: "100%",
  },
  row: {
    marginTop: ms(5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  icon: {
    width: ms(20),
    height: ms(20),
    marginRight: ms(10),
    marginLeft: ms(15)
  },
  leftText: {
    flex: 1,
    textAlign: 'left',
  },
  rightText: {
    flex: 1,
    textAlign: 'right',
    marginRight: ms(15),
  },
  heading: {
    marginTop: ms(10),
    fontSize: ms(18),
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  subText: {
    marginTop: ms(5),
    fontSize: ms(14),
    alignSelf: 'center',
  },

  // Cart Section Styles
  Cart: {
    backgroundColor: "#FFFFFF",
    borderRadius: ms(10),
    borderWidth: 1,
    borderColor: "#cfcfcf",
    width: ms(175),
    marginTop: ms(10),
    marginBottom: ms(20),
    marginLeft: ms(30)
  },
  CartText: {
    padding: ms(15),
    textAlign: "center",
  },
  Carttitle: {
    fontSize: ms(16),
    fontWeight: "bold",
    textAlign: "center",
  },
  CartsubText: {
    fontSize: ms(12),
    color: "gray",
    marginVertical: ms(4),
    textAlign: "center",
  },
  Cartprice: {
    fontSize: ms(20),
    fontWeight: "bold",
    marginVertical: ms(8),
    textAlign: "center",
  },
  Cartprovider: {
    fontSize: ms(12),
    color: "gray",
    marginBottom: ms(12),
    textAlign: "center",
  },
  Cartbutton: {
    backgroundColor: "#1E56A0",
    paddingVertical: ms(10),
    marginTop: ms(20),
    paddingHorizontal: ms(16),
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: ms(10),
    borderBottomRightRadius: ms(10),
    width: "100%",
    alignItems: "center",
  },
  CartbuttonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  headingText1: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: ms(41),
    lineHeight: ms(59),
    backgroundColor: 'transparent',
    color: '#0344af',
    backgroundClip: 'text',
    textFillColor: 'transparent',
    alignSelf: 'left'
  },
  imageContainerFooter: {
    width: "100%",
    height: 'auto',
    alignItems: "center",
  },
  activeButton: {
    backgroundColor: "white", 
  },
  buttonText: {
    fontSize: ms(16),
    color: "#000",
  },
});

export default styles;

